#!/bin/sh

echo ""

DOCUMENT=$1

# Remove old files
if [ -e ${DOCUMENT}.pdf ]
then
  rm ${DOCUMENT}.pdf
fi
if [ -e ${DOCUMENT}.tex ]
then
  rm ${DOCUMENT}.tex
fi
if [ -e log.txt ]
then
  rm log.txt
fi

D1=$(PWD)

if [ -e template.latex ]
then
  DIR=""
else
  cd ..
  if [ -e template.latex ]
  then
    DIR="../"
    cd $D1
  else
    cd ..
    if [ -e template.latex ]
    then
      DIR="../../"
      cd $D1
    else
      cd ..
      if [ -e template.latex ]
      then
        DIR="../../../"
        cd $D1
      fi
    fi
  fi
fi

echo "Converting Markdown to LaTeX ..."
pandoc -f markdown ${DOCUMENT}.md --template=${DIR}template.latex -t latex -o ${DOCUMENT}.tex
if [ -e *.tex ]
then
  echo "Successfully converted Markdown to LaTeX\n"
else
  echo "An error occurred while converting Markdown to LaTeX\n"
  exit 1
fi


if [ -e *.bib ] || [ -e *.bibtex ]
then
  echo "Processing bibliography ..."
  pdflatex ${DOCUMENT}.tex >log.txt
  bibtex ${DOCUMENT}.aux >log.txt
fi

echo "Converting LaTeX to PDF ..."
pdflatex ${DOCUMENT}.tex >log.txt
if [ -e ${DOCUMENT}.pdf ]
then
  echo "50% complete ..."
else
  echo "There are errors in your file.\nPlease consult the log.txt for more information\n"
fi
pdflatex ${DOCUMENT}.tex >log.txt

if [ -e ${DOCUMENT}.pdf ]
then
  echo "LaTeX successfully converted to PDF\n"
else
  echo "PDF build failed.\nThis is most likely an error in your LaTeX commands. Maybe you misspelt a command or package name?\nIf you wish to consult pdfLaTeX's logs, go to log.txt\n"
fi

if [ -e texput.log ]
then
  rm texput.log
fi

# Delete all auxiliary build files generated by LaTeX during the compile step
function delete_aux () {
  if [ -e ${DOCUMENT}.log ]
  then
    rm ${DOCUMENT}.log
  fi
  if [ -e ${DOCUMENT}.aux ]
  then
    rm ${DOCUMENT}.aux
  fi
  if [ -e ${DOCUMENT}.out ]
  then
    rm ${DOCUMENT}.out
  fi
  if [ -e ${DOCUMENT}.toc ]
  then
    rm ${DOCUMENT}.toc
  fi

  # Delete aux bibliography build files if a bibliography exists
  if [ -e *.bib ] || [ -e *.bibtex ]
  then
    rm ${DOCUMENT}.bbl
    rm ${DOCUMENT}.blg
  fi
}

if [ "$2" == "keep-all" ]
then
  echo "Kept all files\n"
elif [ "$2" == "keep-tex" ]
then
  delete_aux
  echo "Kept LaTeX document\n"
else
  delete_aux
  rm ${DOCUMENT}.tex
  echo "Removed all build files\n"
fi